public with sharing class InfosysTriggerQuestion1 {
    public InfosysTriggerQuestion1(List<Case> newCaseList, Map<Id,Case> idVsCaseOldMap, Boolean isInsertOperation) {
        if(isInsertOperation){

            if(newCaseList != NULL){
                for(Case caseObj : newCaseList){
                    if(caseObj.suppliedEmail__c != NULL){

                    }
                }
            }
        }
        else{

        }
    }
    public 
}